### ISSUE TITLE
Switch to this Agenda system

### ISSUE THREAD

**Issue by ferd** [erlef/eef-build-and-packaging-wg#14]
# Background 

Move from the gdocs based agenda to this one

# Tasks

The following tasks must be completed to resolve this issue. 

- [x] Discuss at the WG meeting
- [x] Groom old agenda items
- [x] Update links in invites to refer to this (as a forcing function)

# Related agenda items, issues, and pull requests. 

 - [Feb 5 in the old agenda](https://docs.google.com/document/d/1neU4faTXVA3pz2CMuzIhN-nqrFsPfzO-QhBGdGdbHUU/edit#heading=h.s3wr64ye5d4)
